"""Neon color themes for deutschbuddy Textual app."""

from textual.theme import Theme

NEON_CYBERPUNK_DARK = Theme(
    name="neon_cyberpunk",
    primary="#00F0FF",
    secondary="#FF00FF",
    accent="#00FF9F",
    surface="#0D0D1A",
    background="#0A0A14",
    warning="#FFE600",
    error="#FF2E6E",
    success="#00FF9F",
    foreground="#E0E0FF",
    panel="#12122A",
    dark=True,
    variables={
        "block-cursor-background": "#00F0FF",
        "block-cursor-text-style": "none",
        "footer-key-foreground": "#00F0FF",
        "header-title-foreground": "#00F0FF",
        "header-subtitle-foreground": "#FF00FF",
        "input-selection-background": "#00F0FF 30%",
        "button-primary-background": "#00F0FF",
        "button-primary-foreground": "#0A0A14",
        "button-secondary-background": "#FF00FF",
        "button-secondary-foreground": "#0A0A14",
        "border-title-color": "#00FF9F",
        "border-focus-color": "#00F0FF",
        "app-muted-foreground": "#8A90B8",
        "app-default-border": "#7278A0",
        "app-hover-border": "#00F0FF",
        "app-hover-background": "#161A33",
        "app-hover-foreground": "#E0E0FF",
        "app-focus-border": "#00FF9F",
        "app-focus-background": "#1C2242",
        "app-focus-foreground": "#E0E0FF",
        "app-list-hover-background": "#27214A",
        "app-list-hover-foreground": "#E0E0FF",
        "app-list-highlight-background": "#FF00FF",
        "app-list-highlight-foreground": "#0A0A14",
    },
)

NEON_SUNSET_DARK = Theme(
    name="neon_sunset",
    primary="#FF6B6B",
    secondary="#FFD93D",
    accent="#6BCB77",
    surface="#1A1A2E",
    background="#16162A",
    warning="#FFD93D",
    error="#FF6B6B",
    success="#6BCB77",
    foreground="#FFF5E4",
    panel="#2D2D44",
    dark=True,
    variables={
        "block-cursor-background": "#FF6B6B",
        "block-cursor-text-style": "none",
        "footer-key-foreground": "#FFD93D",
        "header-title-foreground": "#FF6B6B",
        "header-subtitle-foreground": "#FFD93D",
        "input-selection-background": "#FF6B6B 30%",
        "button-primary-background": "#FF6B6B",
        "button-primary-foreground": "#1A1A2E",
        "button-secondary-background": "#FFD93D",
        "button-secondary-foreground": "#1A1A2E",
        "border-title-color": "#6BCB77",
        "border-focus-color": "#FF6B6B",
        "app-muted-foreground": "#B8AB9C",
        "app-default-border": "#A28F80",
        "app-hover-border": "#FF6B6B",
        "app-hover-background": "#3A334C",
        "app-hover-foreground": "#FFF5E4",
        "app-focus-border": "#6BCB77",
        "app-focus-background": "#443652",
        "app-focus-foreground": "#FFF5E4",
        "app-list-hover-background": "#4A3F57",
        "app-list-hover-foreground": "#FFF5E4",
        "app-list-highlight-background": "#FFD93D",
        "app-list-highlight-foreground": "#1A1A2E",
    },
)

NEON_OCEAN_DARK = Theme(
    name="neon_ocean",
    primary="#00D9FF",
    secondary="#7B2CBF",
    accent="#00FF87",
    surface="#0A1628",
    background="#050E1A",
    warning="#FFB703",
    error="#FF4D6D",
    success="#00FF87",
    foreground="#CAF0FF",
    panel="#0D1F35",
    dark=True,
    variables={
        "block-cursor-background": "#00D9FF",
        "block-cursor-text-style": "none",
        "footer-key-foreground": "#00D9FF",
        "header-title-foreground": "#00D9FF",
        "header-subtitle-foreground": "#7B2CBF",
        "input-selection-background": "#00D9FF 30%",
        "button-primary-background": "#00D9FF",
        "button-primary-foreground": "#050E1A",
        "button-secondary-background": "#7B2CBF",
        "button-secondary-foreground": "#CAF0FF",
        "border-title-color": "#00FF87",
        "border-focus-color": "#00D9FF",
        "app-muted-foreground": "#87A7C4",
        "app-default-border": "#5A7FA1",
        "app-hover-border": "#00D9FF",
        "app-hover-background": "#152949",
        "app-hover-foreground": "#CAF0FF",
        "app-focus-border": "#00FF87",
        "app-focus-background": "#183456",
        "app-focus-foreground": "#CAF0FF",
        "app-list-hover-background": "#243A61",
        "app-list-hover-foreground": "#CAF0FF",
        "app-list-highlight-background": "#7B2CBF",
        "app-list-highlight-foreground": "#CAF0FF",
    },
)

NEON_FOREST_DARK = Theme(
    name="neon_forest",
    primary="#39FF14",
    secondary="#FF10F0",
    accent="#00FFFF",
    surface="#0D1A12",
    background="#08110D",
    warning="#FFEA00",
    error="#FF0055",
    success="#39FF14",
    foreground="#D4FFE4",
    panel="#112418",
    dark=True,
    variables={
        "block-cursor-background": "#39FF14",
        "block-cursor-text-style": "none",
        "footer-key-foreground": "#39FF14",
        "header-title-foreground": "#39FF14",
        "header-subtitle-foreground": "#FF10F0",
        "input-selection-background": "#39FF14 30%",
        "button-primary-background": "#39FF14",
        "button-primary-foreground": "#08110D",
        "button-secondary-background": "#FF10F0",
        "button-secondary-foreground": "#D4FFE4",
        "border-title-color": "#00FFFF",
        "border-focus-color": "#39FF14",
        "app-muted-foreground": "#8FB79A",
        "app-default-border": "#6F9A7B",
        "app-hover-border": "#39FF14",
        "app-hover-background": "#1A2A22",
        "app-hover-foreground": "#D4FFE4",
        "app-focus-border": "#00FFFF",
        "app-focus-background": "#203229",
        "app-focus-foreground": "#D4FFE4",
        "app-list-hover-background": "#26362C",
        "app-list-hover-foreground": "#D4FFE4",
        "app-list-highlight-background": "#FF10F0",
        "app-list-highlight-foreground": "#08110D",
    },
)

NEON_MONOCHROME_DARK = Theme(
    name="neon_mono",
    primary="#FFFFFF",
    secondary="#888888",
    accent="#CCCCCC",
    surface="#0A0A0A",
    background="#050505",
    warning="#FFFF00",
    error="#FF0000",
    success="#00FF00",
    foreground="#FFFFFF",
    panel="#111111",
    dark=True,
    variables={
        "block-cursor-background": "#FFFFFF",
        "block-cursor-text-style": "none",
        "footer-key-foreground": "#FFFFFF",
        "header-title-foreground": "#FFFFFF",
        "header-subtitle-foreground": "#888888",
        "input-selection-background": "#FFFFFF 30%",
        "button-primary-background": "#FFFFFF",
        "button-primary-foreground": "#050505",
        "button-secondary-background": "#888888",
        "button-secondary-foreground": "#FFFFFF",
        "border-title-color": "#CCCCCC",
        "border-focus-color": "#FFFFFF",
        "app-muted-foreground": "#A6A6A6",
        "app-default-border": "#7D7D7D",
        "app-hover-border": "#CCCCCC",
        "app-hover-background": "#1E1E1E",
        "app-hover-foreground": "#FFFFFF",
        "app-focus-border": "#FFFFFF",
        "app-focus-background": "#242424",
        "app-focus-foreground": "#FFFFFF",
        "app-list-hover-background": "#2A2A2A",
        "app-list-hover-foreground": "#FFFFFF",
        "app-list-highlight-background": "#888888",
        "app-list-highlight-foreground": "#050505",
    },
)

NEON_RETRO_LIGHT = Theme(
    name="neon_retro",
    primary="#FF00FF",
    secondary="#00FFFF",
    accent="#FF9900",
    surface="#FFF0F5",
    background="#FFFAF0",
    warning="#FF6600",
    error="#FF0066",
    success="#00CC66",
    foreground="#1A1A2E",
    panel="#FFFFFF",
    dark=False,
    variables={
        "block-cursor-background": "#FF00FF",
        "block-cursor-text-style": "none",
        "footer-key-foreground": "#FF00FF",
        "header-title-foreground": "#FF00FF",
        "header-subtitle-foreground": "#00FFFF",
        "input-selection-background": "#FF00FF 25%",
        "button-primary-background": "#FF00FF",
        "button-primary-foreground": "#FFFFFF",
        "button-secondary-background": "#00FFFF",
        "button-secondary-foreground": "#1A1A2E",
        "border-title-color": "#FF9900",
        "border-focus-color": "#FF00FF",
        "app-muted-foreground": "#6E617C",
        "app-default-border": "#9A90A8",
        "app-hover-border": "#FF00FF",
        "app-hover-background": "#F6EAF4",
        "app-hover-foreground": "#1A1A2E",
        "app-focus-border": "#FF9900",
        "app-focus-background": "#F3D8EE",
        "app-focus-foreground": "#1A1A2E",
        "app-list-hover-background": "#E6FBFF",
        "app-list-hover-foreground": "#1A1A2E",
        "app-list-highlight-background": "#00FFFF",
        "app-list-highlight-foreground": "#1A1A2E",
    },
)

ALL_NEON_THEMES = [
    NEON_CYBERPUNK_DARK,
    NEON_SUNSET_DARK,
    NEON_OCEAN_DARK,
    NEON_FOREST_DARK,
    NEON_MONOCHROME_DARK,
    NEON_RETRO_LIGHT,
]

THEME_CHOICES = {
    "neon_cyberpunk": "Neon Cyberpunk (Dark)",
    "neon_sunset": "Neon Sunset (Dark)",
    "neon_ocean": "Neon Ocean (Dark)",
    "neon_forest": "Neon Forest (Dark)",
    "neon_mono": "Neon Monochrome (Dark)",
    "neon_retro": "Neon Retro (Light)",
}
